INSERT INTO gender (id, name) VALUES (2, 'Femenino');
INSERT INTO gender (id, name) VALUES (1, 'Masculino');
INSERT INTO marital_status (id, name) VALUES (1,'Casado');
INSERT INTO marital_status (id, name) VALUES (2,'Viudo');
INSERT INTO marital_status (id, name) VALUES (3,'Divorciado');
INSERT INTO contract_type (id, name) VALUES (1,'Fijo');
INSERT INTO contract_type (id, name) VALUES (2,'Indefinido');
INSERT INTO contract_type (id, name) VALUES (3,'Obra');
INSERT INTO job_type (id, name) VALUES (1,'Developer');
INSERT INTO job_type (id, name) VALUES (2,'Devops');
INSERT INTO job_type (id, name) VALUES (3,'QA');
INSERT INTO job_type (id, name) VALUES (4,'Proyect Manager');
INSERT INTO country (id, name, nationality) VALUES (1, 'Chile', 'Chilena');
INSERT INTO region (id, country_id, name) VALUES (1, 1,'RM');
INSERT INTO city (id, region_id, name) VALUES (1, 1,'Santiago');
INSERT INTO commune (id, city_id, name, sii_code, tgr_code) VALUES (1, 1, 'El Bosque', NULL, NULL);